---
- hosts: all
  gather_facts: False
  become: true

  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)


# Basics
- hosts:  all
  become: true
  roles:
    - bearandgiraffe.base
    - {
      role:           bearandgiraffe.vim,
      vim_username:   '{{ username }}',
      vim_group_name: '{{ group_name }}'
    }
    - {
      role:           bearandgiraffe.node,
      nodejs_version: '{{ node_version }}'
    }
    - bearandgiraffe.phantomjs

# DB
- hosts:  all
  become: true
  roles:
    - {
      role:                   bearandgiraffe.postgresql,
      postgresql_db_name:     '{{ db_name }}',
      postgresql_db_owner:    '{{ db_user }}',
      postgresql_db_password: '{{ db_password }}'
    }

# Remove Apache
- hosts:  all
  user:   vagrant
  tasks:
    - name: Ramove Apache2
      apt: name={{ item }} state=absent purge=yes force=yes
      with_items:
       - apache2
       - apache2-utils
      become: true

# Heroku
- hosts:  all
  become: true
  roles:
    - bearandgiraffe.heroku-cli

- hosts: all
  become: true
  roles:
    - bearandgiraffe.selenium
